### ISSUE TITLE
rubyforge gem missing iso xslt files

### ISSUE THREAD

**Issue by marly** [flazz/schematron#1]
Shouldn't this work after a gem install?

```
require 'schematron'
s = Schematron::Schema.new('my_schematron_file')
s.validate('my_xml_file')
```

Backtrace:

```
Errno::ENOENT: No such file or directory - iso_impl
from /Library/Ruby/Gems/1.8/gems/schematron-0.0.0/lib/schematron.rb:33:in `chdir'
from /Library/Ruby/Gems/1.8/gems/schematron-0.0.0/lib/schematron.rb:33:in `validate'
from /Library/Ruby/Gems/1.8/gems/schematron-0.0.0/lib/schematron.rb:31:in `map'
from /Library/Ruby/Gems/1.8/gems/schematron-0.0.0/lib/schematron.rb:31:in `validate'
from (irb):3
from /Library/Ruby/Gems/1.8/specifications/dm-sweatshop-0.9.11.gemspec:27
```

**Comment by flazz** [comment]
should be fixed in 222ec689206eda53b832bdf26b021b5def3908dd
